name: bsis3a_business_checkin_flutterkick
dependencies:
  cloud_firestore: ^6.3.0
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  firebase_storage: ^13.3.0
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  google_mlkit_text_recognition: ^0.15.1
  image_picker: ^1.2.1
  intl: ^0.18.1
  mobile_scanner: ^7.2.0
environment:
  sdk: '^3.11.0'
flutter:
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^6.0.0
